spring.application.name=auth-service


server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/auth_service_db
spring.datasource.username=root
spring.datasource.password=hassan777

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=4f8e7c1d9a2b6f5e8c3d7a1b9e4f6c2d8a7b5e1c9d3f6a8b2c4e7f1a9d5b3c6
jwt.expiration=3600000